# harness/knowledge/__init__.py — V3.3 Engineering Knowledge Package
"""
Engineering Knowledge package for V3.3.

Provides structured engineering records (PRD, NFR, DR, ADR, TDR, RSK, SEC, RCA)
with provenance, authority, lifecycle, relationships, versioning, validation,
and a deterministic EngineeringKnowledgeGraph for relationship traversal.

Architecture boundaries:
- Engineering Knowledge is separate from Learning Knowledge and Evidence
- Does NOT replace V3.2 learning modules (StructuredExperience, FailureLesson, Strategy, etc.)
- Does NOT replace Evidence modules (EvidencePackage, EvidenceStore)
- Maintains three-domain separation: Engineering Knowledge / Learning Knowledge / Evidence
- EngineeringKnowledgeGraph != CapabilityGraph (no semantics leak)
"""

from .records import (
    EngineeringRecord,
    RecordRelationship,
    RecordError,
    VALID_RECORD_TYPES,
    VALID_RELATIONSHIP_TYPES,
    create_record,
)
from .registry import (
    RECORD_TYPE_CLASSES,
    TYPED_RECORD_CLASSES,
)
from .requirements import (
    PRD,
    Requirement,
    NFR,
    AcceptanceCriterion,
    compute_prd_coverage,
    find_orphan_requirements,
    find_requirements_for_prd,
    find_nfrs_for_requirement,
    find_requirements_constrained_by_nfr,
    detect_requirement_conflicts,
    detect_nfr_conflicts,
    REQ_TYPE_FUNCTIONAL,
    REQ_TYPE_PRODUCT,
    REQ_TYPE_BUSINESS,
    REQ_TYPE_INTEGRATION,
    REQ_TYPE_COMPLIANCE,
    VALID_REQ_TYPES,
    NFR_CATEGORY_PERFORMANCE,
    NFR_CATEGORY_AVAILABILITY,
    NFR_CATEGORY_RELIABILITY,
    NFR_CATEGORY_SECURITY,
    NFR_CATEGORY_SCALABILITY,
    NFR_CATEGORY_MAINTAINABILITY,
    NFR_CATEGORY_OBSERVABILITY,
    NFR_CATEGORY_RECOVERABILITY,
    NFR_CATEGORY_COMPATIBILITY,
    NFR_CATEGORY_PRIVACY,
    VALID_NFR_CATEGORIES,
    NFR_SCOPE_GLOBAL,
    NFR_SCOPE_PRD,
    NFR_SCOPE_REQUIREMENT,
    NFR_SCOPE_COMPONENT,
    VALID_NFR_SCOPES,
    MEASUREMENT_LOAD_TEST,
    MEASUREMENT_UNIT_TEST,
    MEASUREMENT_INTEGRATION_TEST,
    MEASUREMENT_MANUAL_REVIEW,
    MEASUREMENT_MONITORING,
    MEASUREMENT_AUDIT,
    MEASUREMENT_PROFILING,
    VALID_MEASUREMENT_METHODS,
)
from .decisions import (
    DecisionRecord,
    ArchitectureDecisionRecord,
    Alternative,
    Consequences,
    find_supersession_conflicts,
    get_supersession_chain,
    get_effective_decision,
    DECISION_TYPE_ARCHITECTURE,
    DECISION_TYPE_TECHNICAL,
    DECISION_TYPE_SECURITY,
    DECISION_TYPE_PRODUCT,
    DECISION_TYPE_OPERATIONAL,
    DECISION_TYPE_DATA,
    DECISION_TYPE_INTEGRATION,
    VALID_DECISION_TYPES,
    ADR_DOMAIN_DATA,
    ADR_DOMAIN_API,
    ADR_DOMAIN_SECURITY,
    ADR_DOMAIN_DEPLOYMENT,
    ADR_DOMAIN_MESSAGING,
    ADR_DOMAIN_UI,
    ADR_DOMAIN_INFRASTRUCTURE,
    VALID_ADR_DOMAINS,
    DISPOSITION_SELECTED,
    DISPOSITION_REJECTED,
    VALID_DISPOSITIONS,
)
from .risk_security import (
    TechnicalDebtRecord,
    RiskRecord,
    SecurityRecord,
    AuthorityPrecedenceResolver,
    SecurityConflict,
    detect_security_conflicts,
    SecurityAuthorityError,
    validate_security_authority,
    is_security_authority_at_least,
    can_transition_security_authority,
)
from .rca import (
    RCACompleteness,
    FailureKnowledgeCoverage,
    RootCauseAnalysisRecord,
    RCA,
    RCAAnalyzer,
    FailureKnowledgeBridge,
    compute_rca_traceability_metrics,
    RCA_CAUSE_CATEGORY_IMPLEMENTATION,
    RCA_CAUSE_CATEGORY_TEST,
    RCA_CAUSE_CATEGORY_ARCHITECTURE,
    RCA_CAUSE_CATEGORY_SECURITY,
    RCA_CAUSE_CATEGORY_INTEGRATION,
    RCA_CAUSE_CATEGORY_CONFIGURATION,
    RCA_CAUSE_CATEGORY_ENVIRONMENT,
    RCA_CAUSE_CATEGORY_UNKNOWN,
    VALID_RCA_CAUSE_CATEGORIES,
    RCA_STATE_DRAFT,
    RCA_STATE_ANALYSIS,
    RCA_STATE_CORRECTIVE_ACTION,
    RCA_STATE_PREVENTIVE_ACTION,
    RCA_STATE_CLOSED,
    VALID_RCA_STATES,
)
from .risk_security import (
    # TDR constants
    TDR_DEBT_TYPE_CODE,
    TDR_DEBT_TYPE_DESIGN,
    TDR_DEBT_TYPE_ARCHITECTURE,
    TDR_DEBT_TYPE_TEST,
    TDR_DEBT_TYPE_DOCUMENTATION,
    TDR_DEBT_TYPE_DEPENDENCY,
    TDR_DEBT_TYPE_PROCESS,
    TDR_DEBT_TYPE_INFRASTRUCTURE,
    VALID_TDR_DEBT_TYPES,
    TDR_SEVERITY_CRITICAL,
    TDR_SEVERITY_HIGH,
    TDR_SEVERITY_MEDIUM,
    TDR_SEVERITY_LOW,
    VALID_TDR_SEVERITIES,
    TDR_PRIORITY_CRITICAL,
    TDR_PRIORITY_HIGH,
    TDR_PRIORITY_MEDIUM,
    TDR_PRIORITY_LOW,
    VALID_TDR_PRIORITIES,
    # RSK constants
    RSK_CATEGORY_TECHNICAL,
    RSK_CATEGORY_SCHEDULE,
    RSK_CATEGORY_RESOURCE,
    RSK_CATEGORY_SECURITY,
    RSK_CATEGORY_COMPLIANCE,
    VALID_RSK_CATEGORIES,
    RSK_LIKELIHOOD_HIGH,
    RSK_LIKELIHOOD_MEDIUM,
    RSK_LIKELIHOOD_LOW,
    VALID_RSK_LIKELIHOODS,
    RSK_IMPACT_HIGH,
    RSK_IMPACT_MEDIUM,
    RSK_IMPACT_LOW,
    VALID_RSK_IMPACTS,
    VALID_RSK_EXPOSURES,
    # SEC constants
    SEC_CATEGORY_CONSTRAINT,
    SEC_CATEGORY_CONTROL,
    SEC_CATEGORY_FINDING,
    SEC_CATEGORY_THREAT,
    SEC_CATEGORY_REQUIREMENT,
    VALID_SEC_CATEGORIES,
    SEC_AUTHORITY_AUTHORITATIVE,
    SEC_AUTHORITY_ACCEPTED,
    SEC_AUTHORITY_PROPOSED,
    SEC_AUTHORITY_INFERRED,
    SEC_AUTHORITY_HISTORICAL,
    SEC_AUTHORITY_DEPRECATED,
    VALID_SEC_AUTHORITIES,
    SEC_AUTHORITY_RANK,
    PRECEDENCE_GOVERNANCE,
    PRECEDENCE_SECURITY_AUTHORITY,
    PRECEDENCE_AUTHORITATIVE_ENG_KNOWLEDGE,
    PRECEDENCE_ACCEPTED_ENG_KNOWLEDGE,
    PRECEDENCE_TASK_REQUIREMENTS,
    PRECEDENCE_LEARNED_KNOWLEDGE,
    PRECEDENCE_EXPLORATION,
)
from .provenance import (
    Provenance,
    ProvenanceError,
    validate_authority_level,
    is_authority_at_least,
    can_transition_authority,
    AUTHORITY_PROPOSED,
    AUTHORITY_ACCEPTED,
    AUTHORITY_DEPRECATED,
    AUTHORITY_ARCHIVED,
    VALID_AUTHORITY_LEVELS,
    VALID_SOURCES,
)
from .lifecycle import (
    LifecycleError,
    LifecycleTransition,
    get_lifecycle_definition,
    get_initial_state,
    get_terminal_states,
    get_valid_states,
    is_valid_transition,
    transition,
    is_terminal_state,
    get_allowed_transitions,
    validate_lifecycle_state,
    LIFECYCLE_DEFINITIONS,
)
from .store import (
    KnowledgeStore,
    StoreError,
    IntegrityError,
    RecordNotFoundError,
    DuplicateRecordError,
)
from .graph import (
    EngineeringKnowledgeGraph,
    GraphEdge,
    GraphError,
    IntegrityViolation,
    IntegrityConflict,
    TraversalOptions,
    PathResult,
    DEFAULT_TRAVERSAL,
)
from .contradiction import (
    ContradictionDetector,
    ContradictionError,
    CONFLICT_TYPE_DANGLING_REFERENCE,
    CONFLICT_TYPE_INVALID_RELATION,
    CONFLICT_TYPE_FORBIDDEN_CYCLE,
    CONFLICT_TYPE_SUPERSESSION_CONFLICT,
    CONFLICT_TYPE_EXPLICIT_CONTRADICTION,
    CONFLICT_TYPE_STATUS_CONFLICT,
    VALID_CONFLICT_TYPES,
)
from .retrieval import (
    KnowledgeRetriever,
    KnowledgeQuery,
    RetrievalResult,
    RetrievalItem,
    RetrievalMetrics,
    RetrievalError,
    ContextOverflowError,
    KnowledgeConflictError,
)
from .context import (
    KnowledgeContextManager,
    EngineeringKnowledgeContext,
    LearningContext,
    EvidenceContext,
    ContextItem,
    ContextConflictMetadata,
    KnowledgeContextError,
)
from .traceability import (
    TraceabilityService,
    TraceabilityChain,
    TraceabilityEdge,
    TraceabilityMetrics,
    TraceabilityError,
    BrokenTraceError,
)
from .reviewer import (
    KnowledgeReviewer,
    ReviewContext,
    ReviewResult,
    ReviewFinding,
    RequirementResult,
    KnowledgeResult,
    ReviewerError,
    EvidenceFabricationError,
    AuthorityChangeError,
)

__all__ = [
    # Records
    "EngineeringRecord",
    "RecordRelationship",
    "RecordError",
    "PRD",
    "Requirement",
    "NFR",
    "AcceptanceCriterion",
    "TYPED_RECORD_CLASSES",
    "RECORD_TYPE_CLASSES",
    "VALID_RECORD_TYPES",
    "VALID_RELATIONSHIP_TYPES",
    "create_record",
    # Requirements & Coverage
    "compute_prd_coverage",
    "find_orphan_requirements",
    "find_requirements_for_prd",
    "find_nfrs_for_requirement",
    "find_requirements_constrained_by_nfr",
    "detect_requirement_conflicts",
    "detect_nfr_conflicts",
    # Requirement types
    "REQ_TYPE_FUNCTIONAL",
    "REQ_TYPE_PRODUCT",
    "REQ_TYPE_BUSINESS",
    "REQ_TYPE_INTEGRATION",
    "REQ_TYPE_COMPLIANCE",
    "VALID_REQ_TYPES",
    # NFR categories
    "NFR_CATEGORY_PERFORMANCE",
    "NFR_CATEGORY_AVAILABILITY",
    "NFR_CATEGORY_RELIABILITY",
    "NFR_CATEGORY_SECURITY",
    "NFR_CATEGORY_SCALABILITY",
    "NFR_CATEGORY_MAINTAINABILITY",
    "NFR_CATEGORY_OBSERVABILITY",
    "NFR_CATEGORY_RECOVERABILITY",
    "NFR_CATEGORY_COMPATIBILITY",
    "NFR_CATEGORY_PRIVACY",
    "VALID_NFR_CATEGORIES",
    "NFR_SCOPE_GLOBAL",
    "NFR_SCOPE_PRD",
    "NFR_SCOPE_REQUIREMENT",
    "NFR_SCOPE_COMPONENT",
    "VALID_NFR_SCOPES",
    # Measurement methods
    "MEASUREMENT_LOAD_TEST",
    "MEASUREMENT_UNIT_TEST",
    "MEASUREMENT_INTEGRATION_TEST",
    "MEASUREMENT_MANUAL_REVIEW",
    "MEASUREMENT_MONITORING",
    "MEASUREMENT_AUDIT",
    "MEASUREMENT_PROFILING",
    "VALID_MEASUREMENT_METHODS",
    # Provenance
    "Provenance",
    "ProvenanceError",
    "validate_authority_level",
    "is_authority_at_least",
    "can_transition_authority",
    "AUTHORITY_PROPOSED",
    "AUTHORITY_ACCEPTED",
    "AUTHORITY_DEPRECATED",
    "AUTHORITY_ARCHIVED",
    "VALID_AUTHORITY_LEVELS",
    "VALID_SOURCES",
    # Lifecycle
    "LifecycleError",
    "LifecycleTransition",
    "get_lifecycle_definition",
    "get_initial_state",
    "get_terminal_states",
    "get_valid_states",
    "is_valid_transition",
    "transition",
    "is_terminal_state",
    "get_allowed_transitions",
    "validate_lifecycle_state",
    "LIFECYCLE_DEFINITIONS",
    # Store
    "KnowledgeStore",
    "StoreError",
    "IntegrityError",
    "RecordNotFoundError",
    "DuplicateRecordError",
    # Graph
    "EngineeringKnowledgeGraph",
    "GraphEdge",
    "GraphError",
    "IntegrityViolation",
    "IntegrityConflict",
    "TraversalOptions",
    "PathResult",
    "DEFAULT_TRAVERSAL",
    # Contradiction
    "ContradictionDetector",
    "ContradictionError",
    "CONFLICT_TYPE_DANGLING_REFERENCE",
    "CONFLICT_TYPE_INVALID_RELATION",
    "CONFLICT_TYPE_FORBIDDEN_CYCLE",
    "CONFLICT_TYPE_SUPERSESSION_CONFLICT",
    "CONFLICT_TYPE_EXPLICIT_CONTRADICTION",
    "CONFLICT_TYPE_STATUS_CONFLICT",
    "VALID_CONFLICT_TYPES",
    # Retrieval (Phase 8)
    "KnowledgeRetriever",
    "KnowledgeQuery",
    "RetrievalResult",
    "RetrievalItem",
    "RetrievalMetrics",
    "RetrievalError",
    "ContextOverflowError",
    "KnowledgeConflictError",
    # Context (Phase 8)
    "KnowledgeContextManager",
    "EngineeringKnowledgeContext",
    "LearningContext",
    "EvidenceContext",
    "ContextItem",
    "ContextConflictMetadata",
    "KnowledgeContextError",
    # Traceability (Phase 10)
    "TraceabilityService",
    "TraceabilityChain",
    "TraceabilityEdge",
    "TraceabilityMetrics",
    "TraceabilityError",
    "BrokenTraceError",
    # Reviewer (Phase 10)
    "KnowledgeReviewer",
    "ReviewContext",
    "ReviewResult",
    "ReviewFinding",
    "RequirementResult",
    "KnowledgeResult",
    "ReviewerError",
    "EvidenceFabricationError",
    "AuthorityChangeError",
    # Decisions (DR/ADR)
    "DecisionRecord",
    "ArchitectureDecisionRecord",
    "Alternative",
    "Consequences",
    "find_supersession_conflicts",
    "get_supersession_chain",
    "get_effective_decision",
    "DECISION_TYPE_ARCHITECTURE",
    "DECISION_TYPE_TECHNICAL",
    "DECISION_TYPE_SECURITY",
    "DECISION_TYPE_PRODUCT",
    "DECISION_TYPE_OPERATIONAL",
    "DECISION_TYPE_DATA",
    "DECISION_TYPE_INTEGRATION",
    "VALID_DECISION_TYPES",
    "ADR_DOMAIN_DATA",
    "ADR_DOMAIN_API",
    "ADR_DOMAIN_SECURITY",
    "ADR_DOMAIN_DEPLOYMENT",
    "ADR_DOMAIN_MESSAGING",
    "ADR_DOMAIN_UI",
    "ADR_DOMAIN_INFRASTRUCTURE",
    "VALID_ADR_DOMAINS",
    "DISPOSITION_SELECTED",
    "DISPOSITION_REJECTED",
    "VALID_DISPOSITIONS",
    # TDR/RSK/SEC (Phase 6)
    "TechnicalDebtRecord",
    "RiskRecord",
    "SecurityRecord",
    "AuthorityPrecedenceResolver",
    "SecurityConflict",
    "detect_security_conflicts",
    "SecurityAuthorityError",
    # RCA (Phase 7)
    "RootCauseAnalysisRecord",
    "RCA",
    "RCAAnalyzer",
    "FailureKnowledgeBridge",
    "compute_rca_traceability_metrics",
    "RCACompleteness",
    "FailureKnowledgeCoverage",
    "VALID_RCA_CAUSE_CATEGORIES",
    "VALID_RCA_STATES",
    "validate_security_authority",
    "is_security_authority_at_least",
    "can_transition_security_authority",
    # TDR constants
    "TDR_DEBT_TYPE_CODE",
    "TDR_DEBT_TYPE_DESIGN",
    "TDR_DEBT_TYPE_ARCHITECTURE",
    "TDR_DEBT_TYPE_TEST",
    "TDR_DEBT_TYPE_DOCUMENTATION",
    "TDR_DEBT_TYPE_DEPENDENCY",
    "TDR_DEBT_TYPE_PROCESS",
    "TDR_DEBT_TYPE_INFRASTRUCTURE",
    "VALID_TDR_DEBT_TYPES",
    "TDR_SEVERITY_CRITICAL",
    "TDR_SEVERITY_HIGH",
    "TDR_SEVERITY_MEDIUM",
    "TDR_SEVERITY_LOW",
    "VALID_TDR_SEVERITIES",
    "TDR_PRIORITY_CRITICAL",
    "TDR_PRIORITY_HIGH",
    "TDR_PRIORITY_MEDIUM",
    "TDR_PRIORITY_LOW",
    "VALID_TDR_PRIORITIES",
    # RSK constants
    "RSK_CATEGORY_TECHNICAL",
    "RSK_CATEGORY_SCHEDULE",
    "RSK_CATEGORY_RESOURCE",
    "RSK_CATEGORY_SECURITY",
    "RSK_CATEGORY_COMPLIANCE",
    "VALID_RSK_CATEGORIES",
    "RSK_LIKELIHOOD_HIGH",
    "RSK_LIKELIHOOD_MEDIUM",
    "RSK_LIKELIHOOD_LOW",
    "VALID_RSK_LIKELIHOODS",
    "RSK_IMPACT_HIGH",
    "RSK_IMPACT_MEDIUM",
    "RSK_IMPACT_LOW",
    "VALID_RSK_IMPACTS",
    "VALID_RSK_EXPOSURES",
    # SEC constants
    "SEC_CATEGORY_CONSTRAINT",
    "SEC_CATEGORY_CONTROL",
    "SEC_CATEGORY_FINDING",
    "SEC_CATEGORY_THREAT",
    "SEC_CATEGORY_REQUIREMENT",
    "VALID_SEC_CATEGORIES",
    "SEC_AUTHORITY_AUTHORITATIVE",
    "SEC_AUTHORITY_ACCEPTED",
    "SEC_AUTHORITY_PROPOSED",
    "SEC_AUTHORITY_INFERRED",
    "SEC_AUTHORITY_HISTORICAL",
    "SEC_AUTHORITY_DEPRECATED",
    "VALID_SEC_AUTHORITIES",
    "SEC_AUTHORITY_RANK",
    "PRECEDENCE_GOVERNANCE",
    "PRECEDENCE_SECURITY_AUTHORITY",
    "PRECEDENCE_AUTHORITATIVE_ENG_KNOWLEDGE",
    "PRECEDENCE_ACCEPTED_ENG_KNOWLEDGE",
    "PRECEDENCE_TASK_REQUIREMENTS",
    "PRECEDENCE_LEARNED_KNOWLEDGE",
    "PRECEDENCE_EXPLORATION",
]
